modLoader="javafml"
loaderVersion="[42,)"
license="GNU LGPLv3"
[[mods]]
modId="chickensshed"
version="${file.jarVersion}"
displayName="ChickensShed"
displayURL="https://www.curseforge.com/minecraft/mc-mods/chickensshed"
logoFile="logo.png"
authors="holmraven"
description="Chickens shed their feathers occasionally."
[[dependencies.chickensshed]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chickensshed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chickensshed]]
modId = "cloth_config"
mandatory = true
versionRange = "[7,)"
ordering = "NONE"
side = "BOTH"
