modLoader="javafml"
loaderVersion="[36,)"
license="GNU LGPLv3"
[[mods]]
modId="chickensshed"
version="${file.jarVersion}"
displayName="ChickensShed"
authors="holmraven"
description="Chickens shed their feathers occasionally."
[[dependencies.chickensshed]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chickensshed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
